name: peekit_plugins_site
description: "PeekIt Plugins Ecosystem & Marketplace Website"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  kobalt_ui:
    git:
      url: https://github.com/kobaltgit/kobalt_ui.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/registry.json
    - assets/icon.png
    - assets/logo.svg
